# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Workflow
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [12.x, 14.x, 16.x]
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        # name: Use Node.js ${{ matrix.node-version }}
        name: Use Node.js
        with:
          node-version: 16.x
          cache: "yarn"
      - name: 💿 Install dependencies
        run: yarn install --no-immutable"
      - name: ⚒ Build application
        run: yarn build
      - name: 🚀 Deploy
        uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: gh-pages
          folder: build
