name: Deploy
on:
  workflow_call:
    inputs:
      path: 
        required: true
        type: string
      artifact_name:
        required: true
        type: string
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Create deployment scripts"