name: Deploy to Github Pages
on:
  workflow_run:
    workflows: ["Build Workflow"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: gh-pages
          folder: build
