# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD Workflow

on:
  pull_request:
    branches: [main]

jobs:
  build:
    uses: paulfermoreyes/react-todo-app/.github/workflows/build.yml@dev

  deploy:
    needs: build
    uses: paulfermoreyes/react-todo-app/.github/workflows/deploy.yml@dev
    with:
      path: ./build
      artifact_name: build-artifact
