name: Scanner

on:
  pull_request:
    branches: [main]
  workflow_call:
    inputs:
      organization:
        description: "Organization containing the project in SonarCloud"
        default: 'paulfermoreyes'
        required: false
        type: string
      project_key:
        description: "Project key in SonarCloud"
        default: 'react-todo-app'
        required: true
        type: string

jobs:
  scan:
    if: ${{ github.event.label.name == 'scan' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=paulfermoreyes
          -Dsonar.projectKey=react-todo-app
          -Dsonar.sources=.